### ISSUE TITLE
JUCE Module, performance

### ISSUE THREAD

**Issue by timothyschoen** [Archie3d/juce_bgfx#1]
This project looks very promising! I've tried to get JUCE working with nanovg myself for a while, but couldn't get it to work, so great work!

I have a few questions: 

1. Could you format this repo like a JUCE module, so we can easily drop it into projects?

2. Have you tested graphics performance, and is there a noticeable difference? From my own experience, my iPlug2 (nanovg) projects tend to have better graphics performance than my JUCE projects, I wonder if this will bring them up to the same level.

3. Is there a way to use nanovg without bgfx? Only reason I'm asking is bgfx is a very large include compared to nanovg, it would be nice to be able to go without it.

4. What's the licence? Am I allowed to use this in open-source projects if I credit you?

Thanks for making this!

**Comment by Archie3d** [comment]
Hi, to answer your questions:

1. JUCE module format is rather inconvenient to work with should the module have any serious external dependencies. This is somewhat better when using a module with CMake, but obviously won't work with Projucer. So yes, it can be made into a JUCE module but then I'd see it being usable from CMake only. So perhaps I should do that.
2. No, I did not do any thorough testing because the result largely depends on the content to be rendered. For example drawing images will be fast as these are textures preloaded into the GPU, drawing paths however will not be better that using JUCE alone because the path subdivision is done by JUCE anyways before it hits the low level graphics context. Using nanovg directly to paint components (instead of juce::Graphics) will probably be faster in this case, but I do not have any numbers to back this up. Feel free to do some tests, this could be interesting.
3. Yes, originally nanovg is based on OpenGL backend and I don't see and difficulties in using it on top of JUCE's OpenGL. However I do not see much point in doing that, because JUCE renderer is reasonably good already, and OpenGL seems to be a dead-end anyways, at least on desktops. The purpose of this study was to utilise modern backends (Vulkan/Metal), hence bgfx as an easy to use middleware.
4. Please use the code as it suits you. At this stage this is not a plug'n'play reusable library anyways but a POC, there are still lots of limitations in this approach (for example I did not include the code that tracks multiple contexts creation - something that is needed should you want to create multiple plugin instances, for example).

**Comment by timothyschoen** [comment]
Thanks, that answers my questions!

I've tested it a little bit, the performance seems to be pretty good if you reduce the frame-rate. And you can always use the setBufferedToImage flag on Component to make sure paths are rendered as images.

When I was trying to get nanovg working with JUCE, I attached it to a Metal context, using [nanovg_metal](https://github.com/ollix/MetalNanoVG). This does mean you have to find a way to do this for each OS, but this is how iPlug2 does it, so that could be a good reference to use. Not saying that this is the best way (I don't know that much about graphics), but if we could eliminate bgfx, it would suddenly be very easy to turn it into a module as well.

Being able to have multiple instances would be very nice. I'm not very experienced with graphics (but I am with JUCE and C++ otherwise), if I can help in any way let me know, I think this is an interesting proof of concept.

**Comment by timothyschoen** [comment]
Btw, I'm making a version without bgfx here if you're interested: https://github.com/timothyschoen/juce_nanovg

It's largely based on your work, but with just NanoVG for Metal.

JUCE module plans are out the window though, because I don't think there is a way to set up ARC for objc, which is necessary for NVG/Metal.

**Comment by Archie3d** [comment]
Oh, this is great! Perhaps you may consider Vulkan backend (there are ports of nanovg to for Vulkan), this way you'll cover Windows as well.

**Comment by timothyschoen** [comment]
I'll check that out, there's also a d3dx port, that might also be interesting.
